# The base of this file has been taken from
# https://github.com/AmpersandTarski/Ampersand/blob/development/appveyor.yml

# Disable the standard build process which would use MSBuild:
build: off

cache:
- "c:\\sr" # stack root, short paths == less problems
clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

before_build:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
# Appveyor doesn't clone recursively.
- git submodule update --init --recursive

skip_tags: true

build_script:
# Suppress output from stack setup, as there is a lot and it's not necessary.
- stack setup --no-terminal > nul
- stack build --only-snapshot --no-terminal
- stack --local-bin-path . install
- set PATH=%PATH%;C:\stack
- stack exec eta-build -- install

test_script:
- stack test eta
